### ISSUE TITLE
too many threads error,

### ISSUE THREAD

**Issue by atgczcl** [sebas77/Svelto.Tasks#1]
if  you : 
  for (int j = 0; j < 8000; j++)
            {
                pt.Add(new LoadSomething(new WWW("www.google.com")));
            }
will use 
TaskRunner.Instance.AllocateNewTaskRoutine().SetScheduler(_MTRunner).SetEnumerator(pt).Start(); 
, running unity3d crash;
maybe need limit one time run thread count, this will perfect;

**Comment by sebas77** [comment]
Hello, if you use always the same Multithread runner, you will always use one thread. Basically the code fire one thread per Multithread Runner. 

I will check your example asap.

**Comment by sebas77** [comment]
Ok, I tested it and as I imagined, the error is due to the number of threads that Unity creates for WWW. So even if you write 

for (int j = 0; j < 8000; j++)
                DoIT();

 IEnumerator DoIT()
        {
            yield return new WWW("www.google.com");
        }
you will get the same error

**Comment by sebas77** [comment]
I tested it and as I imagined, it's due to the number of threads that Unity creates when WWW is used (one for each WWW). You will get the same error if you use the default Unity approach:

  for (int j = 0; j < 8000; j++)
                StartCoroutine(DoIT());

  IEnumerator DoIT()
        {
            yield return new WWW("www.google.com");
        }
