### ISSUE TITLE
InvalidCastException: Specified cast is not valid.

### ISSUE THREAD

**Issue by Thomas-JZQ** [sebas77/Svelto.Tasks#15]
I just remove the namespace of class "ExampleParallelTasksManagedMT",and modify the name of class "LoadSomething" to "LoadSomething2" ，and construction method also. When i run the demo,i got the error "Specified cast is not valid.".What should i do to solve this problem？Thank you very much for taking time to look at this problem.

![image](https://user-images.githubusercontent.com/13478151/41899910-1b2ff8f8-7960-11e8-9fec-964a6b136bba.png)

![image](https://user-images.githubusercontent.com/13478151/41899954-2dc8fa32-7960-11e8-81f1-284f4b7408dd.png)

![image](https://user-images.githubusercontent.com/13478151/41900193-b6c0f8bc-7960-11e8-89c9-00c0f836f118.png)

![error](https://user-images.githubusercontent.com/13478151/41899867-0b7d0edc-7960-11e8-8fe1-bf513f126e0b.png)

**Comment by sebas77** [comment]
so sorry about it, I didn't think about people using the examples, which I am now messing with, because I am using them to work on Svelto Task 2.0.

I created a new release point to the last commit before 2.0, I didn't have the time to test it, hope it works https://github.com/sebas77/Svelto.Tasks.Tests/releases/tag/1.0

**Comment by Thomas-JZQ** [comment]
Svelto Task 2.0？That is a good news! you realy do a great job. btw, thank you very much for the releases 1.0.

**Comment by sebas77** [comment]
yeah with the new version I am focusing on Allocation 0 code. Let me know if the release works.

**Comment by Thomas-JZQ** [comment]
releases 1.0 … …
![image](https://user-images.githubusercontent.com/13478151/42141122-84ac3cc4-7dd9-11e8-9853-4e6eb6d63427.png)

**Comment by sebas77** [comment]
Be sure you are using the version of svelto that the repository is pointing
at. Unluckily if you just download the zip file the svelto folder is empty.
It should be compatible with the current version on svelto task master tho.
The experimental has been removed in svelto tasks 2 work in progress.

Git is not that friendly when submodules are used...

**Comment by Thomas-JZQ** [comment]
you are right, i do used a wrong version of the submodules , sorry for waste your time on such a problem.  i think "svelto tasks 2" must be better and friendly ,i am full of expectations for your great job.

**Comment by sebas77** [comment]
The new svelto tasks will be more fool proof and faster, but most of the things will be done in a similar way than now.
