### ISSUE TITLE
TaskRunner scene crashes in Unity 5.4.2p4

### ISSUE THREAD

**Issue by MyOwnClone** [sebas77/Svelto.Tasks#2]
When opening TaskRunner scene in 5.4.2p4, scene hierarchy shows only InGameFrameTimer, rest of the objects in hierarchy have no text.

Unity reports around 87 errors like:
"CheckConsistency: GameObject does not reference component MonoBehaviour. Fixing."
or 
"GameObject has multiple Transform components! Merged into single one."
or
"Object GameObject (named '') has multiple entries of the same Object component. Removing it!"

When run, scene crashes whole Unity.

**Comment by sebas77** [comment]
hmm strange, I tested with 5.5, but not with 5.4 lately. I will try this weekend.

**Comment by sebas77** [comment]
it is possible that the scene is not compatible with 5.4 anymore hmm..didn't have the time to try yet.
