### ISSUE TITLE
when i open in unity2018 has some code error

### ISSUE THREAD

**Issue by hico-guo** [sebas77/Svelto.Tasks#20]
1.Assets\Svelto.Tasks\Svelto.Tasks\Collections\TaskCollection.cs(91,31): error CS0411: The type arguments for method 'FasterList<TaskCollection<T>.StructFriendlyStack>.ReuseOneSlot<U>()' cannot be inferred from the usage. Try specifying the type arguments explicitly.
2.Assets\Svelto.Tasks\Svelto.Tasks\Collections\TaskCollection.cs(96,31): error CS1061: 'FasterList<TaskCollection<T>.StructFriendlyStack>' does not contain a definition for 'AddRef' and no accessible extension method 'AddRef' accepting a first argument of type 'FasterList<TaskCollection<T>.StructFriendlyStack>' could be found (are you missing a using directive or an assembly reference?)
how to fix it?

**Comment by sebas77** [comment]
svelto is now only c# 7 compatible. Are you using c# 7? (net 4.0)

**Comment by sebas77** [comment]
can't repro in 2018.4.12, both with master branch or the svelto tasks 2.0 branch. Remember to use c# 7. Be also sure that you sync the submodules properly (this sounds more likely your problem)
