### ISSUE TITLE
Tasks with ecs

### ISSUE THREAD

**Issue by Feldruebe** [sebas77/Svelto.Tasks#25]
Hello,

the current versions of ecs and tasks cannot be used together.
The common sources differ. Is there a work around for this?

**Comment by sebas77** [comment]
Yes, check the survival example in the miniexamples repository. Note that I decided to remove svelto tasks from that example and I am going to commit it probably tomorrow. I will be sure to create a release for future reference

**Comment by sebas77** [comment]
Also if you use svelto please join discord, real time feedback is very useful to us
