### ISSUE TITLE
Svelto.Tasks not functional in UWP Build (Hololens)

### ISSUE THREAD

**Issue by belveder79** [sebas77/Svelto.Tasks#3]
I was trying to embed the taskrunner in an UWP application with Unity 5.5.0f3 (64bit) to have it running on Hololens. Unfortunately the somewhat castrated .NET framework used for UWP causes some errors. I wonder if you can somehow work around that (probably by adding a flag that deactivates some of the features for UWP but keeps the main functionality). Here's the error log:

----------------------

-----CompilerOutput:-stdout--exitcode: 1--compilationhadfailure: True--outfile: Temp/Assembly-CSharp.dll
Microsoft (R) Visual C# Compiler version 1.3.1.60616
Copyright (C) Microsoft Corporation. All rights reserved.

Assets\Scripts\Svelto\DataStructures\SerializableDictionary.cs(23,1): error CS0246: The type or namespace name 'ISerializable' could not be found (are you missing a using directive or an assembly reference?)
Assets\Scripts\Svelto\DataStructures\SerializableDictionary.cs(76,7): error CS0246: The type or namespace name 'ISerializable' could not be found (are you missing a using directive or an assembly reference?)
Assets\Scripts\Svelto\TaskRunner\MonoRunner.cs(90,199): error CS0246: The type or namespace name 'RunnerBehaviour' could not be found (are you missing a using directive or an assembly reference?)
Assets\Scripts\Svelto\TaskRunner\MonoRunner.cs(181,25): error CS0246: The type or namespace name 'RunnerBehaviour' could not be found (are you missing a using directive or an assembly reference?)
Assets\Scripts\Svelto\DataStructures\SerializableDictionary.cs(76,35): error CS0246: The type or namespace name 'SerializationInfo' could not be found (are you missing a using directive or an assembly reference?)
Assets\Scripts\Svelto\DataStructures\SerializableDictionary.cs(76,7): error CS0538: 'ISerializable' in explicit interface declaration is not an interface
Assets\Scripts\Svelto\DataStructures\SerializableDictionary.cs(64,32): error CS0246: The type or namespace name 'SerializationInfo' could not be found (are you missing a using directive or an assembly reference?)
Assets\Scripts\Svelto\TaskRunner\Experimental\ParallelTaskCollection.cs(5,50): error CS0305: Using the generic type 'ParallelTaskCollection<Token>' requires 1 type arguments
Assets\Scripts\Svelto\TaskRunner\Experimental\ParallelTaskCollection.cs(19,33): error CS0115: 'ParallelTaskCollection<Token>.CheckForToken(object)': no suitable method found to override
Assets\Scripts\Svelto\TaskRunner\TaskYieldsIEnumerableException.cs(21,50): error CS0246: The type or namespace name 'SerializationInfo' could not be found (are you missing a using directive or an assembly reference?)
Assets\Scripts\Svelto\DataStructures\WeakReference.cs(54,33): error CS0246: The type or namespace name 'SerializationInfo' could not be found (are you missing a using directive or an assembly reference?)
-----CompilerOutput:-stderr----------
-----EndCompilerOutput---------------
- Finished compile Library/ScriptAssemblies/Assembly-CSharp.dll
Assets\Scripts\Svelto\DataStructures\SerializableDictionary.cs(23,1): error CS0246: The type or namespace name 'ISerializable' could not be found (are you missing a using directive or an assembly reference?)
 
(Filename: Assets\Scripts\Svelto\DataStructures\SerializableDictionary.cs Line: 23)

Assets\Scripts\Svelto\DataStructures\SerializableDictionary.cs(76,7): error CS0246: The type or namespace name 'ISerializable' could not be found (are you missing a using directive or an assembly reference?)
 
(Filename: Assets\Scripts\Svelto\DataStructures\SerializableDictionary.cs Line: 76)

Assets\Scripts\Svelto\TaskRunner\MonoRunner.cs(90,199): error CS0246: The type or namespace name 'RunnerBehaviour' could not be found (are you missing a using directive or an assembly reference?)
 
(Filename: Assets\Scripts\Svelto\TaskRunner\MonoRunner.cs Line: 90)

Assets\Scripts\Svelto\TaskRunner\MonoRunner.cs(181,25): error CS0246: The type or namespace name 'RunnerBehaviour' could not be found (are you missing a using directive or an assembly reference?)
 
(Filename: Assets\Scripts\Svelto\TaskRunner\MonoRunner.cs Line: 181)

Assets\Scripts\Svelto\DataStructures\SerializableDictionary.cs(76,35): error CS0246: The type or namespace name 'SerializationInfo' could not be found (are you missing a using directive or an assembly reference?)
 
(Filename: Assets\Scripts\Svelto\DataStructures\SerializableDictionary.cs Line: 76)

Assets\Scripts\Svelto\DataStructures\SerializableDictionary.cs(76,7): error CS0538: 'ISerializable' in explicit interface declaration is not an interface
 
(Filename: Assets\Scripts\Svelto\DataStructures\SerializableDictionary.cs Line: 76)

Assets\Scripts\Svelto\DataStructures\SerializableDictionary.cs(64,32): error CS0246: The type or namespace name 'SerializationInfo' could not be found (are you missing a using directive or an assembly reference?)
 
(Filename: Assets\Scripts\Svelto\DataStructures\SerializableDictionary.cs Line: 64)

Assets\Scripts\Svelto\TaskRunner\Experimental\ParallelTaskCollection.cs(5,50): error CS0305: Using the generic type 'ParallelTaskCollection<Token>' requires 1 type arguments
 
(Filename: Assets\Scripts\Svelto\TaskRunner\Experimental\ParallelTaskCollection.cs Line: 5)

Assets\Scripts\Svelto\TaskRunner\Experimental\ParallelTaskCollection.cs(19,33): error CS0115: 'ParallelTaskCollection<Token>.CheckForToken(object)': no suitable method found to override
 
(Filename: Assets\Scripts\Svelto\TaskRunner\Experimental\ParallelTaskCollection.cs Line: 19)

Assets\Scripts\Svelto\TaskRunner\TaskYieldsIEnumerableException.cs(21,50): error CS0246: The type or namespace name 'SerializationInfo' could not be found (are you missing a using directive or an assembly reference?)
 
(Filename: Assets\Scripts\Svelto\TaskRunner\TaskYieldsIEnumerableException.cs Line: 21)

Assets\Scripts\Svelto\DataStructures\WeakReference.cs(54,33): error CS0246: The type or namespace name 'SerializationInfo' could not be found (are you missing a using directive or an assembly reference?)
 
(Filename: Assets\Scripts\Svelto\DataStructures\WeakReference.cs Line: 54)

DisplayProgressNotification: Build Failed
Error building Player because scripts had compiler errors
 
(Filename:  Line: -1)

---------------------------

**Comment by sebas77** [comment]
Thanks, SerializableDictionary is not needed and I will delete it soon, you can do the same. For the rest a fix will come soon.

**Comment by belveder79** [comment]
awesome! can't wait :-)

**Comment by sebas77** [comment]
btw if you use IL2CPP it should work, but I will try to port for the .net platform as well. Shouldn't be too hard. I'll work on it this weekend.

**Comment by sebas77** [comment]
ok now it compiles, as long as you delete the nunit dependencies and unit tests (or just don't compile the example, but only the lib)
