### ISSUE TITLE
How to stop/reset running task

### ISSUE THREAD

**Issue by purepure** [sebas77/Svelto.Tasks#4]
Hi!
This lib is really helpful and I am using it as core of my game components. I have a list of task to run but I cannot stop/reset/clear the current collection of task to run the another one.

the input is: SerialTaskCollection serialTasks (with a list of Itask)
then I run: TaskRunner.Instance.Run (serialTasks);
Now how to stop this long task to start new one ?

Please tell me how!

**Comment by sebas77** [comment]
Hello,

sorry I just noticed this message. Only the ITaskRoutine can be stopped, so you need to create one using             _task = TaskRunner.Instance.AllocateNewTaskRoutine(); Then you can use a serial task as Enumerator or Enumerator provider. Now you can stop it.
Let me know if it's not clear please.

**Comment by purepure** [comment]
Thank!
I already did it. Now with your confirmation, I confident to use it.
One more thing: Can we monitor what task is running?access to each task(SerialTaskCollection) to modify data while _task is running. (I.e: sometime we need to remove all the task, that was finished or need to know the last task is running)

I tried to access them but I hasn't found any function in SerialTaskCollection to do it. Anyway ?

**Comment by sebas77** [comment]
Can you write in pseudo code what you would like to do so I can understand
better the use case?

**Comment by purepure** [comment]
var runner = TaskRunner.Instance.AllocateNewTaskRoutine();
var serialTasks = new SerialTaskCollection();

//cmd = ITask
//cmds is ArrayList<ITask>
foreach (var cmd in cmds) {
    serialTasks.Add(cmd);
}
//start the chain
runner.SetEnumerator(serialTasks).Start();


//now I want to know which cmd is running to modify data and remove all the completed task out of the serialTasks. Incase I stop the runner: runner.Stop();, I want to know which's the last task(ITask) or which task is the runner stopped at?

Please tell me if there is anything not clear

**Comment by sebas77** [comment]
The completed tasks are automatically removed from the collections, while I still not sure what you mean about modifying the task data. I need an example

**Comment by purepure** [comment]
ah, I have a list of task. some of them depend on what happened on the previous's result and data from server send to client. For example, when runner run at task 4th, my client receive some data from server and want to modify data of  the chain (from what stopped at) to the end. That is reason why I need to know where is my task stopped at and ability to modify data.

My temporary solution is create an ArrayList and access them via reference. Any suggestion?

**Comment by sebas77** [comment]
if I understood correctly (I may have not) you need to pass data generated by a task to the next tasks in the chain. 

I started to work on this feature, but I never really polished it as I never had a real use case so far. The class SerialTaskCollection < Token > allows to pass an object between tasks, following more or less the chain of responsibility pattern. Let me know if this may be useful for you.

Alternatively I may (didn't think through) code a system that would let pass the result of an enumator to the next one, but I am not sure if it's actually a good idea.

**Comment by purepure** [comment]
Yeah, that is exactly what I am working on. I need to pass/update data to the SerialTaskCollection. Btw, The SerialTaskCollection (as my thought) lack of some functions to access the information such as Get current running task, getTaskAtIndex,...and so on.

That is my thinking. 

I am working on a solution: using an ArrayList as reference combine with monitoring task in TaskRunner(to know what task is running. Each Itask I design a callback when it finished). If I want to update data, I just simply update that list and re-create new SerialTaskCollection and start over. 
Do you think it is ok?

**Comment by sebas77** [comment]
Why don't you use the Svelto.Tasks.Experimental.SerialTaskCollection< Token > functionality then? (sorry the token part was eaten before)

**Comment by purepure** [comment]
I read the tutorial at http://www.sebaslab.com/svelto-taskrunner-run-serial-and-parallel-asynchronous-tasks-in-unity3d/ and haven't seen that collection. I will check it out. 

Thank for supporting me.
You did a good job

**Comment by purepure** [comment]
Just check around, there is only public function
public TaskCollection Add(ITaskChain<Token> task)

There is no function to GetTask or visit entire the collection.

**Comment by sebas77** [comment]
thanks! Following the link, the example is the last one where you can read:

 serialTasks1 = new SerialTaskCollection<ValueObject>(vo);
            parallelTasks1 = new ParallelTaskCollection<ValueObject>(vo);
            serialTasks2 = new SerialTaskCollection<ValueObject>(vo);
            parallelTasks2 = new ParallelTaskCollection<ValueObject>(vo);

remember, it's an experimental feature, but if it works for you, let me know so I can improve it if you need it.

**Comment by purepure** [comment]
(y)
Thank!

**Comment by purepure** [comment]
Sorry again!
As I checked that collection, it allow to pass data to ITask but not publish function to access directly element of collection.
What do you think about to add function as Get/SetTask(atIndex), GetCurrentRunningTask() to support for loop in order to visit/access all the task from TaskCollection. It help to manage/monitor the TaskRunner easier. I am understanding TaskCollection as a kind of List/ArrayList.

Above is just my thought, not sure it match your road map or not.
At the end, thank you a lot for this lib.

**Comment by sebas77** [comment]
so the problem is that getting a specific task from the collection is not a good idea. I have the impression that what you want to do can be done inverting the logic, therefore without managing the task directly, but from within the task and/or the collection itself. If the Token solution doesn't help you, it means I still didn't understand what you need :(. If I understood it correctly, you needed to change the behavior of a running collection according some data. This you can do with the Token, as one task can change the value of the token and the next tasks decide how to behave according this value. For example they could quit immediately instead to execute logic. 

The implementation is still too naive probably, but if I extend it, would this be a solution for you?

**Comment by purepure** [comment]
Yeah, the token could help me resolve my current issue. 
The only reason why I keep asking to add those functions is I am thinking about the TaskCollection's behavior. I add ITask into a TaskCollection and think: this is a collection so that I can add/remove task or modify element as a List. So the flow is simple like that: I have a list of task, and the runner will visit one by one to execute according the token. If I want to change some thing, Just get it directly from the list to modify. -> it is more handy and straight(I think)  than making some thing to control the token and the token will affect to the ITask. Btw, if TaskCollection provides function to get its element and also the current running task's index, it can act like a real collection type like ArrayList.
If I want to access the token of Task at index [index], how can I do?. Because sometime, we need to jump directly to a task not following the order.

> The implementation is still too naive probably, but if I extend it, would this be a solution for you?

The current implementation is good enough to go, my asking is just like a comment to make it more handy to control/access the Collection's element. It is up to you.
BR

**Comment by sebas77** [comment]
yes ok I now understand. Maybe I made a mistake to call thme collections. As user, you shouldn't know what the task runner decides to do with the collection itself. For example, currently, the task are removed from the list, so the index content would change. You may inherit from a TaskCollection and create your own logic, but that's the furthest I would go. The structure shouldn't be known outside the collection itself, so you shouldn't expose it through public functions. Of course this is my suggestion, but you can shape the code as you wish. If you come up with something nice, let me know!

**Comment by purepure** [comment]
I understand the concept of your collection now. It is ok to go since it remove the task when it is done. My code base also work with your current implementation.

Good job man!
