### ISSUE TITLE
Show Exception Stack Trace

### ISSUE THREAD

**Issue by leopripos** [sebas77/Svelto.Tasks#8]
https://github.com/sebas77/Svelto.Tasks/blob/87f0332b5cfa22739ace58ccc9003f4ebc737470/Assets/Scripts/Svelto/TaskRunner/PausableTask.cs#L192

Should change like this

> Utility.Console.LogError(e.Message, e.StackTrace);

**Comment by sebas77** [comment]
Yes fixed already in my local code to e.ToString()

**Comment by sebas77** [comment]
finally commited, thanks for reporting
